name: mysqldb

services:
    db:
      image: mysql
      restart: always
      ports: 
        - 40000:3306
      environment:
        MYSQL_USER: app
        MYSQL_PASSWORD: test1234
        MYSQL_DATABASE: app
        MYSQL_ROOT_PASSWORD: test1234

